name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: lakshmi1327
        password: Thmlp@321

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: my-docker-repo/my-app:latest

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
